---
title: "02_clean.qmd"
format: html
editor: visual
---

# Load libraries

```{r}
library(lubridate)
library(dplyr)
library(janitor)
library(data.table)
```

# Clean Data

## Clean HC patient data

```{r}

# Remove rows that do not correspond to patients and last column called "Notes" 
hc_patient_data <- hc_patient_data |> 
  slice(1:80) |> select(1:28)

# Make variable type as Date
hc_patient_data <- hc_patient_data |> 
  mutate(DOB = ymd(DOB))
```

### Give shorter names to the variables renaming them

```{r}

# Remove spaces from variable names 
hc_patient_data <- hc_patient_data |> 
  clean_names()

# Rename variables 
change_variable_names <- c(
  date_of_birth = "dob",
  grading_system = "ctcae_4_0_hematuria_grade",
  comorbidities = "comorbidities_dm_stroke_pvd_cirrhosis_drug_abuse_alcoholism_tobacco_hx_mi_last_6mo_chf_copd_esrd",
  cancer_type = "type_bladder_prostate_pathologic_clinial_staging_of_cancer",
  radiation_type = "type_of_radation",
  radiation_dosage = "dose_of_radation_gy",
  start_end_radiation = "start_date_of_radiation_end_date_of_radiation",
  number_of_admissions = "number_of_admissions_including_er_visits_requiring_urology_consultation",
  number_of_icu_admits = "number_of_icu_admits_with_hemorrhgic_cystits",
  radiation_completion_to_first_hc = "time_passed_since_completion_of_radiation_treatment_months_and_first_incidence_hc",
  number_of_cystoscopies = "number_of_cystoscopies_with_clot_evacuation_and_or_fulguration_of_bleeders",
  formalin_instillation = "number_of_times_requiring_formalin_instillation",
  alum_instillation = "number_of_times_requiring_alum_instillation",
  silver_nit_instillation = "number_of_times_requiring_silver_nitrate_instillation",
  amicar_instillation = "number_of_times_requiring_amicar_instillation",
  hyperbaric_o2 = "number_times_requiring_hyperbaric_o2_tx_days",
  surgery_for_urinary_diversion = "surgery_for_urinary_diversion_required_if_yes_what_type",
  number_transfusions = "number_of_units_of_p_rb_cs_tranfused",
  hospitalization_complications = "complications_during_hospitalization_uti_pyelonephritis_urosepsis_hydronephrosis_aki_other"
)

hc_patient_data <- rename(hc_patient_data, any_of(change_variable_names))
```

### Correct mistakes in the variable classes

```{r}

## ethnicity - make all names lower case, change AA to african american
hc_patient_data <- hc_patient_data |> 
  mutate(ethnicity = ifelse(ethnicity == "AA", "african_american", tolower(ethnicity)))

## hospital_site - remove spaces and separate different hospitals by comas, correct names 
hc_patient_data <- hc_patient_data |> 
  mutate(hospital_site = str_replace_all(hospital_site, " ", ""),
         hospital_site = str_replace_all(hospital_site, "/", ","),
         hospital_site = str_replace(hospital_site, "Harperr", "Harper"))


## radiation_dosage - remove characters "Gy" make the observatons as num
hc_patient_data <- hc_patient_data |> 
  mutate(radiation_dosage =  str_replace_all(radiation_dosage, "Gy", ""),
         radiation_dosage = round(as.numeric(radiation_dosage),2)) 

```

### Write the clean data in a CSV file and save it in data

```{r}
write.csv(hc_patient_data, 
          file = "~/group_18_project/data/clean_hc_patient_data.csv", 
          row.names = FALSE)
```

## Clean patients_1 and patients_2 data

```{r}
# Remove spaces from variable names 
patient_info1 <- patient_info1 |> 
    clean_names()

patient_info2 <- patient_info2 |> 
    clean_names()

# Remove Unknown column from the variables and columns that don't exist in patient_info2
patient_info1 <- patient_info1 |> 
  select(-unknown, 
         -rads_for_prostate_primary, 
         -rads_bladder_primary, 
         -developed_bladder_first,
         -developed_prostate_first)

# Remove Unknown column
patient_info2 <- patient_info2 |> 
  select(-unknown)

# Replace N/A with 0 and X or x with 1
patient_info1 <- patient_info1 |>
   mutate_all(~ ifelse(is.na(.) | tolower(.) == "na", 0, 
                       ifelse(tolower(.) == "x", 1, .)))

patient_info2 <- patient_info2 |> 
   mutate_all(~ ifelse(is.na(.) | tolower(.) == "na", 0, 
                       ifelse(tolower(.) == "x", 1, .)))

# Change variable in patient_info1 blader_ca to blader as in patient_info2
patient_info1 <- patient_info1 |>
  rename(bladder = "bladder_ca")

# Merge patient_info1 and patient_info2
combined_patient_info <- bind_rows(patient_info1, patient_info2)
```

### Write the clean data in a CSV file and save it in data

```{r}
write.csv(combined_patient_info, 
          file = "~/group_18_project/data/clean_patient_info.csv", 
          row.names = FALSE)
```
