---
title: "04_augment.qmd"
format: html
editor: visual
---

# Load clean data

```{r}
# OLD -  from csv file
clean_hc_patient_data <- read_csv(file = "~/group_18_project/data/clean_hc_patient_data.csv")

# NEW - from tsv file
clean_data1 <- read_tsv(
  file = "~/group_18_project/data/02_dat_clean1.tsv",
  show_col_types = FALSE)
```

# Augment

Make new columns cancer_organ and cancer_stage from cancer_type, removing the later afterwards

```{r}

## cancer_type is separated into new variables and then removed 
clean_hc_patient_data <- clean_hc_patient_data |>
  mutate(
    cancer_organ = case_when(
      grepl("prostate", tolower(cancer_type)) & grepl("bladder", tolower(cancer_type)) ~       "prostate,bladder",
      grepl("prostate", tolower(cancer_type)) ~ "prostate",
      grepl("bladder", tolower(cancer_type)) ~ "bladder",
      TRUE ~ NA_character_),
    cancer_stage = str_extract(cancer_type, "(?i)T\\d++[a-z]|Gleason \\d+")) |>
  select(-cancer_type)
```

BMI (Laia)

```{r}

```

Divide comorbidities into columns

```{r}

```

### Data Wrangling: Hospitalization complications

Comput the sum fo hopitalization complications and add is as a new columns called: " "

```{r}


```
